# Generated by Django 4.1 on 2022-09-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_details',
            name='doj',
        ),
    ]
